wrapper_mapper_impl.h - disable VS 2022 warning as error introduced May 2025
detail/impl/wrapper_mapper_impl.h(91): error C2220: the following warning is treated as an error
detail/impl/wrapper_mapper_impl.h(91): warning C4506: no definition for inline function 'std::reference_wrapper<double> rttr::wrapper_mapper<_Ty>::create(double &)'
        with
        [
            _Ty=std::reference_wrapper<double>
        ]